# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifier.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0enotifier.proto"z\n\rNotifyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x12\n\nrecipients\x18\x03 \x03(\t\x12\x14\n\x0cmessage_type\x18\x05 \x01(\t\x12\x1d\n\x15notification_channels\x18\x06 \x03(\t"\x84\x01\n\x0eNotifyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x12\n\nrecipients\x18\x03 \x03(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x1d\n\x15notification_channels\x18\x07 \x03(\t2>\n\x0fNotifierService\x12+\n\x06Notify\x12\x0e.NotifyRequest\x1a\x0f.NotifyResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "notifier_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_NOTIFYREQUEST"]._serialized_start = 18
    _globals["_NOTIFYREQUEST"]._serialized_end = 140
    _globals["_NOTIFYRESPONSE"]._serialized_start = 143
    _globals["_NOTIFYRESPONSE"]._serialized_end = 275
    _globals["_NOTIFIERSERVICE"]._serialized_start = 277
    _globals["_NOTIFIERSERVICE"]._serialized_end = 339
# @@protoc_insertion_point(module_scope)
