# Generated by Django 4.2.11 on 2024-04-14 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='attendance_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual'), ('INTERESTED', 'Interested'), ('REGISTERED', 'Registered')], max_length=100), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
