# Generated by Django 4.2.11 on 2024-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_categories_remove_event_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
